channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - dask
  - nodejs
  - graphviz
  - numpy
  - scikit-image
  - dask[complete]
  - dask-image
  - ipykernel
  - matplotlib
  - distributed
  - google-colab
  - pandas
  - scipy
  - requests
  - toolz
  - tornado>=6.1
  - zarr
  - xarray
  - fsspec>=0.8.4
  - ipympl
  - ipywidgets>=7.5.1
  - ipython>=8.3.0
  - ipycanvas
  - coiled
  - wasmer
  - pip:
    - imjoy-jupyter-extension
    - ome-zarr
    - multiscale_spatial_image
    - itk>=5.3rc4
    - itkwidgets>=0.32.1
    - tifffile
    - graphviz
