channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - dask
  - nodejs
  - graphviz
  - itkwidgets>=0.32.0
  - numpy
  - itk>=5.1.1
  - scikit-image
  - dask[complete]
  - dask-image
  - ipykernel
  - distributed
  - pandas
  - scipy
  - requests
  - toolz
  - zarr
  - xarray
  - fsspec>=0.8.4
  - ipympl
  - ipywidgets>=7.5.1
  - coiled
  - pyimagej
  - openjdk=8
  - z5py
  - pip:
    - nbdev
    - imjoy-jupyter-extension
    - ome-zarr
    - ipycanvas
